name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json

      # 1) Генерируем lock под Linux (не ставит node_modules)
      - name: Regenerate lockfile for Linux
        if: runner.os == 'Linux'
        run: |
          rm -f package-lock.json
          npm i --package-lock-only --no-audit --no-fund

      # 2) Чистая установка строго по linux-lock'у
      - name: Clean install (npm ci)
        run: |
          rm -rf node_modules
          npm ci

      # 3) Подстраховка: убедимся, что подтянулся бинарник Rollup для Linux
      - name: Ensure Rollup Linux binary
        if: runner.os == 'Linux'
        run: |
          npm ls @rollup/rollup-linux-x64-gnu || npm i -D @rollup/rollup-linux-x64-gnu@^4 --no-save
          npm ls @rollup/rollup-linux-x64-gnu

      # 4) Сборка
      - name: Build
        run: npm run build

      # SPA-роутинг: копируем index.html → 404.html
      - name: Create 404.html for SPA routing
        run: cp dist/index.html dist/404.html

      # Настройка Pages и загрузка артефакта
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
